"""initial schema

Revision ID: a865d9915db1
Revises: 
Create Date: 2026-08-24 12:37:35.480884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a865d9915db1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='classification'), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('require_alert', sa.Boolean(), nullable=False),
    sa.Column('require_masking', sa.Boolean(), nullable=False),
    sa.Column('require_watermark', sa.Boolean(), nullable=False),
    sa.Column('require_footer', sa.Boolean(), nullable=False),
    sa.Column('allow_printing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classification')
    )
    op.create_table('detection_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('requires_keyword_context', sa.Boolean(), nullable=False),
    sa.Column('context_keywords', sa.String(length=1000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rules_category'), 'detection_rules', ['category'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_category'), 'keywords', ['category'], unique=False)
    op.create_table('printers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.Enum('IPP', 'SOCKET', name='printerprotocol'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('ipp_path', sa.String(length=255), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', name='printerstatus'), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_weights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('print_jobs',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'ANALYZING', 'DETECTED', 'CLASSIFIED', 'AWAITING_DECISION', 'SANITIZING', 'READY', 'PRINTING', 'COMPLETED', 'BLOCKED', 'CANCELLED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('action', sa.Enum('PENDING', 'ALLOW_PRINT', 'MASK_AND_PRINT', 'CANCELLED', 'BLOCKED', name='jobaction'), nullable=False),
    sa.Column('block_reason', sa.Enum('NONE', 'SCANNED_DOCUMENT', 'PROCESSING_FAILURE', 'POLICY_DENIED', 'USER_CANCELLED', name='blockreason'), nullable=False),
    sa.Column('status_message', sa.String(length=500), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='classification'), nullable=True),
    sa.Column('original_path', sa.String(length=1000), nullable=True),
    sa.Column('sanitized_path', sa.String(length=1000), nullable=True),
    sa.Column('printer_id', sa.String(length=36), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.Enum('JOB_RECEIVED', 'ANALYSIS_STARTED', 'NO_TEXT_LAYER', 'DATA_DETECTED', 'RISK_SCORED', 'CLASSIFIED', 'AWAITING_DECISION', 'DECISION_CANCEL', 'DECISION_MASK', 'SANITIZING', 'SANITIZED', 'REDACTION_VERIFICATION_FAILED', 'RELEASED_TO_PRINTER', 'PRINT_COMPLETED', 'PRINT_FAILED', 'PRINTER_TESTED', 'BLOCKED', 'FAILED', 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', name='auditeventtype'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('detection_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['print_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_summaries')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('print_jobs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('risk_weights')
    op.drop_table('printers')
    op.drop_index(op.f('ix_keywords_category'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_detection_rules_category'), table_name='detection_rules')
    op.drop_table('detection_rules')
    op.drop_table('classification_policies')
    # ### end Alembic commands ###
