import enum


class UserRole(str, enum.Enum):
    USER = "USER"
    ADMIN = "ADMIN"


class Classification(str, enum.Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class JobStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    ANALYZING = "ANALYZING"
    DETECTED = "DETECTED"
    CLASSIFIED = "CLASSIFIED"
    AWAITING_DECISION = "AWAITING_DECISION"
    SANITIZING = "SANITIZING"
    READY = "READY"
    PRINTING = "PRINTING"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class JobAction(str, enum.Enum):
    PENDING = "PENDING"
    ALLOW_PRINT = "ALLOW_PRINT"
    MASK_AND_PRINT = "MASK_AND_PRINT"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"


class BlockReason(str, enum.Enum):
    NONE = "NONE"
    SCANNED_DOCUMENT = "SCANNED_DOCUMENT"
    PROCESSING_FAILURE = "PROCESSING_FAILURE"
    POLICY_DENIED = "POLICY_DENIED"
    USER_CANCELLED = "USER_CANCELLED"


class PrinterStatus(str, enum.Enum):
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    UNKNOWN = "UNKNOWN"


class PrinterProtocol(str, enum.Enum):
    IPP = "IPP"  # Internet Printing Protocol over HTTP(S), port 631 by convention
    SOCKET = "SOCKET"  # Raw AppSocket / JetDirect streaming, port 9100 by convention


class AuditEventType(str, enum.Enum):
    JOB_RECEIVED = "JOB_RECEIVED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    NO_TEXT_LAYER = "NO_TEXT_LAYER"
    DATA_DETECTED = "DATA_DETECTED"
    RISK_SCORED = "RISK_SCORED"
    CLASSIFIED = "CLASSIFIED"
    AWAITING_DECISION = "AWAITING_DECISION"
    DECISION_CANCEL = "DECISION_CANCEL"
    DECISION_MASK = "DECISION_MASK"
    SANITIZING = "SANITIZING"
    SANITIZED = "SANITIZED"
    REDACTION_VERIFICATION_FAILED = "REDACTION_VERIFICATION_FAILED"
    RELEASED_TO_PRINTER = "RELEASED_TO_PRINTER"
    PRINT_COMPLETED = "PRINT_COMPLETED"
    PRINT_FAILED = "PRINT_FAILED"
    PRINTER_TESTED = "PRINTER_TESTED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    TOKEN_CREATED = "TOKEN_CREATED"
    TOKEN_REVOKED = "TOKEN_REVOKED"
